# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages
warnings_are_errors: true

## Tweaks to default build configuration
##
## gifski (required by gganimate) requires cargo
## newer gcc/g++ to try to avoid weird Eigen bug
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cargo
      - gcc-8
      - g++-8
      - gfortran-8

env:
  global:
    - MAKEFLAGS="-j 2"
    - CXX=g++-8
    - CC=gcc-8

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 100
  - mkdir -p ~/.R
  - echo 'CC=gcc-8' > ~/.R/Makevars; echo "CXX=g++-8" >> ~/.R/Makevars
  - cat ~/.R/Makevars
  - Rscript -e "source('build_steps.R'); before_install()"

after_success:
   - Rscript -e "source('build_steps.R'); after_success(); unlink('build_steps.R')"
   - Rscript -e 'if(Sys.info()["sysname"] != "Linux"){q()}; library(covr); flags <- getOption("covr.flags"); flags[] <- gsub("-O0 ", "", flags); options(covr.flags=flags); codecov(quiet=FALSE)'

branches:
  except:
    - master # Don't build "master" branch or we get in an infinite loop

r_build_args: --no-manual --no-resave-data
r_check_args: --no-manual

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
  local_dir: .
  target_branch: master
  condition: $TRAVIS_OS_NAME = "linux"
